//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.02 at 04:52:26 PM CEST 
//




import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ROW" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="_Structure_key" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="_Parent_key" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="_StructureName_key" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="_Stage_key" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="edinburghKey" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="printName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="treeDepth" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="printStop" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="topoSort" type="{http://www.w3.org/2001/XMLSchema}String"/>
 *                   &lt;element name="structureNote" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="creation_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="modification_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
		"structureKey",
		"parentKey",
		"structureNameKey",
		"stageKey",
		"edinburghKey",
		"printName",
		"treeDepth",
		"printStop",
		"topoSort",
		"structureNote",
		"creationDate",
		"modificationDate"
})
public class ROW {

	@XmlElement(name = "ROW")
	protected List<ROW> row;
	@XmlElement(name = "_Structure_key")
	protected String structureKey;
	@XmlElement(name = "_Parent_key")
	protected String parentKey;
	@XmlElement(name = "_StructureName_key")
	protected String structureNameKey;
	@XmlElement(name = "_Stage_key")
	protected String stageKey;
	protected String edinburghKey;
	@XmlElement(required = true)
	protected String printName;
	protected String treeDepth;
	protected String printStop;
	protected String topoSort;
	@XmlElement(required = true)
	protected String structureNote;
	@XmlElement(name = "creation_date", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar creationDate;
	@XmlElement(name = "modification_date", required = true)
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar modificationDate;
	private List<ROW> children;

	public List<ROW> getROW() {
		if (row == null) {
			row = new ArrayList<ROW>();
		}
		return this.row;
	}
	/**
	 * Gets the value of the structureKey property.
	 * 
	 */
	public String getStructureKey() {
		return structureKey;
	}

	/**
	 * Sets the value of the structureKey property.
	 * 
	 */
	public void setStructureKey(String value) {
		this.structureKey = value;
	}

	/**
	 * Gets the value of the parentKey property.
	 * 
	 */
	public String getParentKey() {
		return parentKey;
	}

	/**
	 * Sets the value of the parentKey property.
	 * 
	 */
	public void setParentKey(String value) {
		this.parentKey = value;
	}

	/**
	 * Gets the value of the structureNameKey property.
	 * 
	 */
	public String getStructureNameKey() {
		return structureNameKey;
	}

	/**
	 * Sets the value of the structureNameKey property.
	 * 
	 */
	public void setStructureNameKey(String value) {
		this.structureNameKey = value;
	}

	/**
	 * Gets the value of the stageKey property.
	 * 
	 */
	public String getStageKey() {
		return stageKey;
	}

	/**
	 * Sets the value of the stageKey property.
	 * 
	 */
	public void setStageKey(String value) {
		this.stageKey = value;
	}

	/**
	 * Gets the value of the edinburghKey property.
	 * 
	 */
	public String getEdinburghKey() {
		return edinburghKey;
	}

	/**
	 * Sets the value of the edinburghKey property.
	 * 
	 */
	public void setEdinburghKey(String value) {
		this.edinburghKey = value;
	}

	/**
	 * Gets the value of the printName property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getPrintName() {
		return printName;
	}

	/**
	 * Sets the value of the printName property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setPrintName(String value) {
		this.printName = value;
	}

	/**
	 * Gets the value of the treeDepth property.
	 * 
	 */
	public String getTreeDepth() {
		return treeDepth;
	}

	/**
	 * Sets the value of the treeDepth property.
	 * 
	 */
	public void setTreeDepth(String value) {
		this.treeDepth = value;
	}

	/**
	 * Gets the value of the printStop property.
	 * 
	 */
	public String getPrintStop() {
		return printStop;
	}

	/**
	 * Sets the value of the printStop property.
	 * 
	 */
	public void setPrintStop(String value) {
		this.printStop = value;
	}

	/**
	 * Gets the value of the topoSort property.
	 * 
	 */
	public String getTopoSort() {
		return topoSort;
	}

	/**
	 * Sets the value of the topoSort property.
	 * 
	 */
	public void setTopoSort(String value) {
		this.topoSort = value;
	}

	/**
	 * Gets the value of the structureNote property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getStructureNote() {
		return structureNote;
	}

	/**
	 * Sets the value of the structureNote property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setStructureNote(String value) {
		this.structureNote = value;
	}

	/**
	 * Gets the value of the creationDate property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link XMLGregorianCalendar }
	 *     
	 */
	public XMLGregorianCalendar getCreationDate() {
		return creationDate;
	}

	/**
	 * Sets the value of the creationDate property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link XMLGregorianCalendar }
	 *     
	 */
	public void setCreationDate(XMLGregorianCalendar value) {
		this.creationDate = value;
	}

	/**
	 * Gets the value of the modificationDate property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link XMLGregorianCalendar }
	 *     
	 */
	public XMLGregorianCalendar getModificationDate() {
		return modificationDate;
	}

	/**
	 * Sets the value of the modificationDate property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link XMLGregorianCalendar }
	 *     
	 */
	public void setModificationDate(XMLGregorianCalendar value) {
		this.modificationDate = value;
	}
	public List<ROW> getChildren() {
		return children;
	}

	/**
	 * Sets the value of the children property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Children }
	 *     
	 */
	public void addChild(ROW value) {
		this.children.add(value);
	}

	public boolean isChild(String parentName)
	{
		if(getStructureKey().equals(parentName))
		{
			return true;
		}
		else
		{
			return false;
		}
	}

}

